# .github/labeler.yml

# Matches any changes inside the frontend directory
frontend:
  - changed-files:
      - any-glob-to-any-file: "web/**/*"

# Matches any changes inside the backend directory
backend:
  - changed-files:
      - any-glob-to-any-file: "backend/**/*"

# Matches changes to GitHub workflows, actions, or this config file
ci-cd:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
