# Generated by Django 6.0.2 on 2026-06-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_ai_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('TICKET_CREATED', 'Ticket Created'), ('TICKET_UPDATED', 'Ticket Updated'), ('TICKET_DELETED', 'Ticket Deleted'), ('TICKET_ASSIGNED', 'Ticket Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('COMMENT_ADDED', 'Comment Added'), ('ATTACHMENT_ADDED', 'Attachment Added'), ('ATTACHMENT_DELETED', 'Attachment Deleted'), ('CATEGORY_CREATED', 'Category Created'), ('CATEGORY_UPDATED', 'Category Updated'), ('CATEGORY_DELETED', 'Category Deleted'), ('TAG_CREATED', 'Tag Created'), ('TAG_UPDATED', 'Tag Updated'), ('TAG_DELETED', 'Tag Deleted'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_PROFILE_UPDATED', 'User Profile Updated'), ('USER_PASSWORD_CHANGED', 'User Password Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
