# Generated by Django 6.0.2 on 2026-05-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team assignment for EMPLOYEE role (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='departments.team'),
        ),
    ]
