# Generated by Django 6.0.2 on 2026-06-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
