version: '3.8'

services:
  db:
    image: postgres:15
    container_name: helpdesk_postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=helpdesk_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password123
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: helpdesk_redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: helpdesk_django_app
    command: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # Django database settings
      - DB_HOST=db
      - DB_NAME=helpdesk_db
      - DB_USER=admin
      - DB_PASSWORD=password123
      # Redis settings for Channel Layers
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

volumes:
  postgres_data: