# Generated by Django 6.0.2 on 2026-05-05 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Department name (e.g., 'IT Support', 'Billing')", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description and responsibilities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive departments don't accept new assignments")),
                ('manager', models.ForeignKey(blank=True, help_text='Department manager (typically MANAGER role)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Team name (e.g., 'Desktop Support')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Team responsibilities and specialization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive teams don't accept new assignments")),
                ('department', models.ForeignKey(help_text='Parent department', on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='departments.department')),
                ('team_lead', models.ForeignKey(blank=True, help_text='Team lead or senior employee (usually EMPLOYEE or MANAGER)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'name'],
                'unique_together': {('name', 'department')},
            },
        ),
    ]
